
title: Roman Chugunov # your title
url: 'https://romanchugunov.co.uk'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: Roman Chugunov  ## put your name
location: London, UK


## Social Profiles
facebook: https://www.facebook.com/chugunov.r/  ## your facebook account url
linkedin: https://www.linkedin.com/in/rchugunov/  ## your linkedin account url



# Update all the sections by editing the files inside _includes folder.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
